#ifndef VERSION_H
#define VERSION_H

#define LC_VERSION_MAJOR 0
#define LC_VERSION_MINOR 1
#define LC_VERSION_BUILD 1
#define LC_VERSION_REVISION 57
#define LC_VERSION LC_VERSION_MAJOR.LC_VERSION_MINOR.LC_VERSION_BUILD.LC_VERSION_REVISION

#endif // VERSION_H